### ISSUE TITLE
Can you help how to solve my problem with my prediction 

### ISSUE THREAD

**Issue by marcusau** [billpku/NLP_In_Action#10]
I was training my NER model with 'bert-base-chinese'

    ##Load model
    model = BertForTokenClassification.from_pretrained(bert_out_address,num_labels=24)
    
    vocabulary = bert_out_address+os.sep+"vocab.txt"
    max_len  = 216
    tokenizer=BertTokenizer(vocab_file=vocabulary,do_lower_case=False)

    

    test_sentences='瑞幸幕後老闆陸正耀是福建屏南人，資本「神州系」是福建企業'

    input_ ="[CLS] "+test_sentences+" [SEP]"
    print(input_)
    
[CLS] 瑞幸幕後老闆陸正耀是福建屏南人，資本「神州系」是福建企業 [SEP]

     tokenized_texts = []
     tokenized_texts.append('[CLS]')

     for word in test_sentences:

        token_list = tokenizer.tokenize(word)
        for token in enumerate(token_list):
             tokenized_texts.append(token[1])
     tokenized_texts.append('[SEP]') 

['[CLS]', '瑞', '幸', '幕', '後', '老', '闆', '陸', '正', '耀', '是', '福', '建', '屏', '南', '人', '，', '資', '本', '「', '神','州','系', '」', '是', '福', '建', '企', '業', '[SEP]']

    input_ids = pad_sequences([[tokenizer.convert_tokens_to_ids(txt) for txt in tokenized_texts]], maxlen=max_len, dtype="long", truncating="post", padding="post")
    print(input_ids[0])

[ 101 4448 2401 2391 2527 5439 7293 7380 3633 5438 3221 4886 2456 2242
 1298  782 8024 6536 3315  519 4868 2336 5143  520 3221 4886 2456  821
 3511  102    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]

    # For fine tune of predict, with token mask is 1,pad token is 0
    attention_masks = [[int(i>0) for i in ii] for ii in input_ids]
    print(attention_masks[0])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
216

    with torch.no_grad():
            outputs = model(input_ids, token_type_ids=None, attention_mask=attention_masks,)
        
            logits = outputs[0] 
    
           # Get NER predict result
            logits = torch.argmax(F.log_softmax(logits,dim=2),dim=2)
            logits = logits.detach().cpu().numpy()
    
    
           # Get NER true result
            label_ids = label_ids.to('cpu').numpy()
    
    
          # Only predict the real word, mark=0, will not calculate
            input_mask = input_mask.to('cpu').numpy()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-8b6e74b073cc> in <module>()
      1 with torch.no_grad():
----> 2         outputs = model(input_ids, token_type_ids=None, attention_mask=attention_masks,)
      3         # For eval mode, the first result of outputs is logits
      4         logits = outputs[0]
      5 

3 frames
/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask)
    689             raise ValueError("You cannot specify both input_ids and inputs_embeds at the same time")
    690         elif input_ids is not None:
--> 691             input_shape = input_ids.size()
    692         elif inputs_embeds is not None:
    693             input_shape = inputs_embeds.size()[:-1]

TypeError: 'int' object is not callable

**Comment by billpku** [comment]
@marcusau 

Hi,

Sorry for the late reply.
According to your case,  had you tried "attention_mask=None"， leaving only the token ids embedding as predict model input？

In order to help you to solve the problem, I had updated my notebook adding inference support:
- [NER_with_BERT.ipynb](https://github.com/billpku/NLP_In_Action/blob/master/NER_with_BERT.ipynb)

Hope this can help you.
As always, feel free to leave a comment.
