### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by jashokkumar83** [billpku/NLP_In_Action#11]
I have tried the original repo. But I get the following issues in the Load XLNet model.

```
`# In this document, contain confg(txt) and weight(bin) files
model_file_address = '/content/drive/MyDrive/models/xlnet-base-cased/xlnet-base-cased-pytorch_model.bin'
model = XLNetForSequenceClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))`
```

```
`UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-54-995a203df40d> in <module>()
      3 # Download model from "https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-pytorch_model.bin"
      4 # Download model from "https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-config.json"
----> 5 model = XLNetForSequenceClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))

3 frames
/usr/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`
```

Any help, please? Thank you in advance

**Comment by Viraj1901181** [comment]
I am facing the same problem. could anyone help me?

**Comment by billpku** [comment]
> I have tried the original repo. But I get the following issues in the Load XLNet model.
> 
> ```
> `# In this document, contain confg(txt) and weight(bin) files
> model_file_address = '/content/drive/MyDrive/models/xlnet-base-cased/xlnet-base-cased-pytorch_model.bin'
> model = XLNetForSequenceClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))`
> ```
> 
> ```
> `UnicodeDecodeError                        Traceback (most recent call last)
> <ipython-input-54-995a203df40d> in <module>()
>       3 # Download model from "https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-pytorch_model.bin"
>       4 # Download model from "https://s3.amazonaws.com/models.huggingface.co/bert/xlnet-base-cased-config.json"
> ----> 5 model = XLNetForSequenceClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))
> 
> 3 frames
> /usr/lib/python3.6/codecs.py in decode(self, input, final)
>     319         # decode input (taking the buffer into account)
>     320         data = self.buffer + input
> --> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
>     322         # keep undecoded input until the next call
>     323         self.buffer = data[consumed:]
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`
> ```
> 
> Any help, please? Thank you in advance

@jashokkumar83

Hi Jash,

Sorry for the late reply.

I found that you pick a wrong ```model_file_address```
you can change your code:
```
model_file_address = '/content/drive/MyDrive/models/xlnet-base-cased/xlnet-base-cased-pytorch_model.bin'
```

into
```
model_file_address = '/content/drive/MyDrive/models/xlnet-base-cased/'
```
Hope that it work for you.

Since ```XLNetForSequenceClassification.from_pretrained``` will load the model bin and config file,  not only the bin file.
And also make sure these files are in your ```'/content/drive/MyDrive/models/xlnet-base-cased/'``` folder, and rename the file as below:

- vocab.txt - vocabulary file (Optional)
- pytorch_model.bin - the PyTorch-compatible (and converted) model (Must)
- config.json - json-based model configuration (Must)


for more info, you can check out here: https://github.com/huggingface/transformers/issues/1620


Feel free to leave a comment if you have any question.

**Comment by billpku** [comment]
> I am facing the same problem. could anyone help me?

@Viraj1901181 

You can check out my replay for Jash above.
Hope that it will work for you.
